FROM golang:1.20.6-alpine3.18 AS builder

WORKDIR /go/src/github.com/and3rson/dunai
RUN go install github.com/cosmtrek/air@v1.44.0
COPY go.mod go.sum ./
RUN go mod download -x
COPY cmd ./cmd
COPY dunai ./dunai
