FROM golang:1.16.5-alpine AS builder

WORKDIR /go/src/github.com/and3rson/dunai
RUN go get github.com/cosmtrek/air
COPY *.go go.mod go.sum ./
COPY data ./data
COPY static ./static
COPY templates ./templates
RUN go get
