version: '3'

services:
  app:
    image: dunai-dev
    build:
      context: .
      dockerfile: Dockerfile.dev
    # environment:
    #   POSTGRES_URI: psql://dunai:dunai@db/dunai
    command: air
    restart: always
    volumes:
      - ./:/go/src/github.com/and3rson/dunai
      - ./certs:/var/lib/gemini/certs
    ports:
      - 8888:8888
      - 1965:1965
    # depends_on:
    #   - db

  # db:
  #   image: postgres:9.6
  #   environment:
  #     POSTGRES_DB: dunai
  #     POSTGRES_USER: dunai
  #     POSTGRES_PASSWORD: dunai
